apiVersion: apps/v1
kind: Deployment
metadata:
  name: knjizenje-service
  namespace: racunovodstvo-dev
  labels:
    app: knjizenje-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knjizenje-service
  template:
    metadata:
      labels:
        app: knjizenje-service
    spec:
      containers:
        - image: ghcr.io/raf-si-2021/racunovodstvo-knjizenje:latest
          name: racunovodstvo-knjizenje-service
          imagePullPolicy: Always
          ports:
            - name: knjizenje
              containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MYSQL_MASTER_HOST
              value: "jdbc:mysql://database-primary-0.database-primary-headless.racunovodstvo-dev:3306/knjizenje?serverTimezone=UTC"
            - name: MYSQL_SLAVE_HOST
              value: "jdbc:mysql://database-secondary-0.database-secondary-headless.racunovodstvo-dev:3306/knjizenje?serverTimezone=UTC"
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
            - name: MYSQL_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_SLAVE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: REGISTRY_HOST
              value: "eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: knjizenje-service
  namespace: racunovodstvo-dev
  labels:
    app: knjizenje-service
spec:
  type: ClusterIP
  selector:
    app: knjizenje-service
  ports:
    - port: 8081
      protocol: TCP
      targetPort: knjizenje
