apiVersion: apps/v1
kind: Deployment
metadata:
  name: preduzece
  namespace: racunovodstvo-dev
  labels:
    app: preduzece
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preduzece
  template:
    metadata:
      labels:
        app: preduzece
    spec:
      serviceAccount: discovery-client
      containers:
        - image: ghcr.io/raf-si-2021/racunovodstvo-preduzece:dev
          name: racunovodstvo-preduzece-service
          imagePullPolicy: Always
          ports:
            - name: preduzece
              containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MYSQL_MASTER_HOST
              value: "jdbc:mysql://database-primary-0.database-primary-headless.racunovodstvo-dev:3306/preduzece?serverTimezone=UTC"
            - name: MYSQL_SLAVE0_HOST
              value: "jdbc:mysql://database-secondary-0.database-secondary-headless.racunovodstvo-dev:3306/preduzece?serverTimezone=UTC"
            - name: MYSQL_SLAVE1_HOST
              value: "jdbc:mysql://database-secondary-1.database-secondary-headless.racunovodstvo-dev:3306/preduzece?serverTimezone=UTC"
            - name: MYSQL_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_SLAVE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: preduzece
  namespace: racunovodstvo-dev
  labels:
    app: preduzece
spec:
  type: ClusterIP
  selector:
    app: preduzece
  ports:
    - port: 8083
      protocol: TCP
      targetPort: preduzece
