apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: racunovodstvo-dev
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      serviceAccount: discovery-client
      containers:
        - image: ghcr.io/raf-si-2021/racunovodstvo-user:latest
          name: racunovodstvo-user-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: user
              containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MYSQL_MASTER_HOST
              value: "jdbc:mysql://database-primary-0.database-primary-headless.racunovodstvo-dev:3306/user?serverTimezone=UTC"
            - name: MYSQL_SLAVE_HOST
              value: "jdbc:mysql://database-secondary-0.database-secondary-headless.racunovodstvo-dev:3306/user?serverTimezone=UTC"
            - name: MYSQL_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_SLAVE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: racunovodstvo-dev
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 8082
      protocol: TCP
      targetPort: user
