---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: discovery-client
      namespace: racunovodstvo-prod
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: discovery-client:view
      namespace: racunovodstvo-prod
    roleRef:
      kind: Role
      apiGroup: rbac.authorization.k8s.io
      name: namespace-reader
    subjects:
      - kind: ServiceAccount
        name: discovery-client
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      namespace: racunovodstvo-prod
      name: namespace-reader
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["services", "endpoints"]
        verbs: ["get", "list", "watch"]
