apiVersion: apps/v1
kind: Deployment
metadata:
  name: nabavka
  namespace: racunovodstvo-prod
  labels:
    app: nabavka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nabavka
  template:
    metadata:
      labels:
        app: nabavka
    spec:
      serviceAccount: discovery-client
      containers:
        - image: ghcr.io/raf-si-2021/racunovodstvo-nabavka:latest
          name: nabavka
          imagePullPolicy: Always
          ports:
            - name: nabavka
              containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: MYSQL_MASTER_HOST
              value: "jdbc:mysql://database-primary-0.database-primary-headless.racunovodstvo-prod:3306/nabavka?serverTimezone=UTC"
            - name: MYSQL_SLAVE0_HOST
              value: "jdbc:mysql://database-secondary-0.database-secondary-headless.racunovodstvo-prod:3306/nabavka?serverTimezone=UTC"
            - name: MYSQL_SLAVE1_HOST
              value: "jdbc:mysql://database-secondary-1.database-secondary-headless.racunovodstvo-prod:3306/nabavka?serverTimezone=UTC"
            - name: MYSQL_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_SLAVE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: nabavka
  namespace: racunovodstvo-prod
  labels:
    app: nabavka
spec:
  type: ClusterIP
  selector:
    app: nabavka
  ports:
    - port: 8084
      protocol: TCP
      targetPort: nabavka
